version: '2'
services:
  imap-backup:
    image: theohbrothers/docker-imap-backup:latest
    volumes:
      - imap-backup:/root/.imap-backup
    networks:
      - default
    stop_signal: SIGKILL
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
          set -eu

          # Run at 00:00 daily. To customize your cron schedule, use https://crontab.guru
          crontab - <<'EOF'
          0 0 * * * imap-backup backup
          EOF

          echo "Running crond"
          exec crond -f

networks:
  default:

volumes:
  imap-backup:
